// Generated by CoffeeScript 1.6.3
(function() {
  var Pool;

  Pool = (function() {
    function Pool(cons, size) {
      this._consfn = cons;
      this._size = size;
      this._pool = [];
    }

    Pool.prototype.get = function() {
      return this._consfn();
    };

    Pool.prototype.release = function(x) {};

    return Pool;

  })();

  exports.Pool = Pool;

}).call(this);
